import type { UpstreamModule } from "./upstream-inventory.js";

export type ParityStatus = "implemented" | "partial" | "planned";

export interface ParityEntry {
  readonly implementationOrigin: "not-started" | "original";
  readonly method: string;
  readonly module: UpstreamModule;
  readonly notes: string;
  readonly sources: readonly string[];
  readonly status: ParityStatus;
  readonly upstream: string;
  readonly upstreamId: string;
  readonly wasmExport?: string;
}

export interface ParityManifest {
  readonly baseline: string;
  readonly baselineSource: string;
  readonly entries: readonly ParityEntry[];
  readonly inventoryPolicy: string;
  readonly packageVersion: string;
  readonly schemaVersion: 2;
}

const CORE_ARRAY_SOURCE = "https://docs.opencv.org/4.13.0/d2/de8/group__core__array.html";
const CORE_SOURCE = "https://docs.opencv.org/4.13.0/d0/de1/group__core.html";
const FEATURES2D_SOURCE = "https://docs.opencv.org/4.13.0/da/d9b/group__features2d.html";
const IMGPROC_COLOR_SOURCE =
  "https://docs.opencv.org/4.13.0/d8/d01/group__imgproc__color__conversions.html";
const IMGPROC_TRANSFORM_SOURCE =
  "https://docs.opencv.org/4.13.0/da/d54/group__imgproc__transform.html";
const IMGPROC_MISC_SOURCE = "https://docs.opencv.org/4.13.0/d7/d1b/group__imgproc__misc.html";
const IMGPROC_HISTOGRAM_SOURCE = "https://docs.opencv.org/4.13.0/d6/dc7/group__imgproc__hist.html";
const IMGPROC_SOURCE = "https://docs.opencv.org/4.13.0/d7/dbd/group__imgproc.html";
const PHOTO_SOURCE = "https://docs.opencv.org/4.13.0/d1/d0d/group__photo.html";

export const PARITY_MANIFEST = {
  baseline: "OpenCV.js 4.13.0 public browser bindings",
  baselineSource: "https://github.com/opencv/opencv/blob/4.13.0/platforms/js/opencv_js.config.py",
  entries: [
    {
      implementationOrigin: "original",
      method: "createAKAZE",
      module: "features2d",
      notes:
        "Creates a Rust-owned AKAZE configuration handle with the OpenCV 4.13 defaults and optional descriptor, threshold, octave, diffusivity, and maximum-point settings; the official 4.13.0 artifact omits the config-listed static AKAZE.create binding, so direct factory comparison is unavailable, and feature detection, descriptor extraction, and broader lifetime audits remain.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.AKAZE.create",
      upstreamId: "features2d.akaze.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getDefaultName",
      module: "features2d",
      notes:
        "Returns Feature2D.AKAZE with exact pinned-browser arity, return value, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getDefaultName",
      upstreamId: "features2d.akaze.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getDescriptorChannels",
      module: "features2d",
      notes:
        "Reads the complete signed i32 descriptor-channel state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getDescriptorChannels",
      upstreamId: "features2d.akaze.get-descriptor-channels",
      wasmExport: "getDescriptorChannels",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getDescriptorSize",
      module: "features2d",
      notes:
        "Reads the complete signed i32 descriptor-size state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getDescriptorSize",
      upstreamId: "features2d.akaze.get-descriptor-size",
      wasmExport: "getDescriptorSize",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getDescriptorType",
      module: "features2d",
      notes:
        "Returns the canonical pinned-browser descriptor-type enum singleton with exact identity, arity, argument errors, unknown-wire behavior, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getDescriptorType",
      upstreamId: "features2d.akaze.get-descriptor-type",
      wasmExport: "getDescriptorType",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getDiffusivity",
      module: "features2d",
      notes:
        "Returns the shared canonical pinned-browser diffusivity enum singleton with exact identity, arity, argument errors, unknown-wire behavior, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getDiffusivity",
      upstreamId: "features2d.akaze.get-diffusivity",
      wasmExport: "getDiffusivity",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getNOctaveLayers",
      module: "features2d",
      notes:
        "Reads the complete signed i32 octave-layer state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getNOctaveLayers",
      upstreamId: "features2d.akaze.get-noctave-layers",
      wasmExport: "getNOctaveLayers",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getNOctaves",
      module: "features2d",
      notes:
        "Reads the complete signed i32 octave-count state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getNOctaves",
      upstreamId: "features2d.akaze.get-noctaves",
      wasmExport: "getNOctaves",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.getThreshold",
      module: "features2d",
      notes:
        "Reads the complete F64 threshold state, including negative zero and non-finite values, with exact pinned-browser arity, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.getThreshold",
      upstreamId: "features2d.akaze.get-threshold",
      wasmExport: "getThreshold",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setDescriptorChannels",
      module: "features2d",
      notes:
        "Updates the complete signed i32 descriptor-channel state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setDescriptorChannels",
      upstreamId: "features2d.akaze.set-descriptor-channels",
      wasmExport: "setDescriptorChannels",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setDescriptorSize",
      module: "features2d",
      notes:
        "Updates the complete signed i32 descriptor-size state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setDescriptorSize",
      upstreamId: "features2d.akaze.set-descriptor-size",
      wasmExport: "setDescriptorSize",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setDescriptorType",
      module: "features2d",
      notes:
        "Stores the structural enum object's signed i32 wire value with exact coercion, undefined return, argument errors, unknown values, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setDescriptorType",
      upstreamId: "features2d.akaze.set-descriptor-type",
      wasmExport: "setDescriptorType",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setDiffusivity",
      module: "features2d",
      notes:
        "Stores the structural diffusivity object's signed i32 wire value with exact coercion, undefined return, argument errors, unknown values, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setDiffusivity",
      upstreamId: "features2d.akaze.set-diffusivity",
      wasmExport: "setDiffusivity",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setNOctaveLayers",
      module: "features2d",
      notes:
        "Updates the complete signed i32 octave-layer state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setNOctaveLayers",
      upstreamId: "features2d.akaze.set-noctave-layers",
      wasmExport: "setNOctaveLayers",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setNOctaves",
      module: "features2d",
      notes:
        "Updates the complete signed i32 octave-count state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setNOctaves",
      upstreamId: "features2d.akaze.set-noctaves",
      wasmExport: "setNOctaves",
    },
    {
      implementationOrigin: "original",
      method: "AKAZE.setThreshold",
      module: "features2d",
      notes:
        "Updates the complete F64 threshold state, including negative zero and non-finite values, with exact pinned-browser number coercion, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AKAZE.setThreshold",
      upstreamId: "features2d.akaze.set-threshold",
      wasmExport: "setThreshold",
    },
    {
      implementationOrigin: "original",
      method: "createKAZE",
      module: "features2d",
      notes:
        "Creates a Rust-owned KAZE configuration handle with the OpenCV 4.13 defaults and optional extended, upright, threshold, octave, and diffusivity settings; the official 4.13.0 artifact omits the config-listed static KAZE.create binding, so direct factory comparison is unavailable, and feature detection and descriptor extraction remain.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.KAZE.create",
      upstreamId: "features2d.kaze.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getDefaultName",
      module: "features2d",
      notes:
        "Returns Feature2D.KAZE with exact pinned-browser arity, return value, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getDefaultName",
      upstreamId: "features2d.kaze.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getDiffusivity",
      module: "features2d",
      notes:
        "Returns the shared canonical pinned-browser diffusivity enum singleton with exact identity, arity, argument errors, unknown-wire behavior, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getDiffusivity",
      upstreamId: "features2d.kaze.get-diffusivity",
      wasmExport: "getDiffusivity",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getExtended",
      module: "features2d",
      notes:
        "Reads the Rust-owned extended-descriptor flag with exact pinned-browser arity, boolean state, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getExtended",
      upstreamId: "features2d.kaze.get-extended",
      wasmExport: "getExtended",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getNOctaveLayers",
      module: "features2d",
      notes:
        "Reads the complete signed i32 octave-layer state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getNOctaveLayers",
      upstreamId: "features2d.kaze.get-noctave-layers",
      wasmExport: "getNOctaveLayers",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getNOctaves",
      module: "features2d",
      notes:
        "Reads the complete signed i32 octave-count state with exact pinned-browser arity, return values, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getNOctaves",
      upstreamId: "features2d.kaze.get-noctaves",
      wasmExport: "getNOctaves",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getThreshold",
      module: "features2d",
      notes:
        "Reads the complete F64 threshold state, including negative zero and non-finite values, with exact pinned-browser arity, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getThreshold",
      upstreamId: "features2d.kaze.get-threshold",
      wasmExport: "getThreshold",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.getUpright",
      module: "features2d",
      notes:
        "Reads the Rust-owned upright-descriptor flag with exact pinned-browser arity, boolean state, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.getUpright",
      upstreamId: "features2d.kaze.get-upright",
      wasmExport: "getUpright",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setDiffusivity",
      module: "features2d",
      notes:
        "Stores the structural diffusivity object's signed i32 wire value with exact coercion, undefined return, argument errors, unknown values, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setDiffusivity",
      upstreamId: "features2d.kaze.set-diffusivity",
      wasmExport: "setDiffusivity",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setExtended",
      module: "features2d",
      notes:
        "Updates the Rust-owned extended-descriptor flag with exact pinned-browser boolean coercion, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setExtended",
      upstreamId: "features2d.kaze.set-extended",
      wasmExport: "setExtended",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setNOctaveLayers",
      module: "features2d",
      notes:
        "Updates the complete signed i32 octave-layer state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setNOctaveLayers",
      upstreamId: "features2d.kaze.set-noctave-layers",
      wasmExport: "setNOctaveLayers",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setNOctaves",
      module: "features2d",
      notes:
        "Updates the complete signed i32 octave-count state with exact pinned-browser integer coercion, range errors, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setNOctaves",
      upstreamId: "features2d.kaze.set-noctaves",
      wasmExport: "setNOctaves",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setThreshold",
      module: "features2d",
      notes:
        "Updates the complete F64 threshold state, including negative zero and non-finite values, with exact pinned-browser number coercion, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setThreshold",
      upstreamId: "features2d.kaze.set-threshold",
      wasmExport: "setThreshold",
    },
    {
      implementationOrigin: "original",
      method: "KAZE.setUpright",
      module: "features2d",
      notes:
        "Updates the Rust-owned upright-descriptor flag with exact pinned-browser boolean coercion, undefined return, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.KAZE.setUpright",
      upstreamId: "features2d.kaze.set-upright",
      wasmExport: "setUpright",
    },
    {
      implementationOrigin: "original",
      method: "createMSER",
      module: "features2d",
      notes:
        "Creates a Rust-owned MSER configuration handle with pinned defaults; the official 4.13.0 artifact omits the config-listed static MSER.create binding, and detectRegions remains unimplemented.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.MSER.create",
      upstreamId: "features2d.mser.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "MSER.getDefaultName",
      module: "features2d",
      notes: "Exact pinned-browser name, arity, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.getDefaultName",
      upstreamId: "features2d.mser.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "MSER.getDelta",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.getDelta",
      upstreamId: "features2d.mser.get-delta",
      wasmExport: "getDelta",
    },
    {
      implementationOrigin: "original",
      method: "MSER.getMaxArea",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.getMaxArea",
      upstreamId: "features2d.mser.get-max-area",
      wasmExport: "getMaxArea",
    },
    {
      implementationOrigin: "original",
      method: "MSER.getMinArea",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.getMinArea",
      upstreamId: "features2d.mser.get-min-area",
      wasmExport: "getMinArea",
    },
    {
      implementationOrigin: "original",
      method: "MSER.getPass2Only",
      module: "features2d",
      notes: "Exact pinned-browser boolean state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.getPass2Only",
      upstreamId: "features2d.mser.get-pass2-only",
      wasmExport: "getPass2Only",
    },
    {
      implementationOrigin: "original",
      method: "MSER.setDelta",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.setDelta",
      upstreamId: "features2d.mser.set-delta",
      wasmExport: "setDelta",
    },
    {
      implementationOrigin: "original",
      method: "MSER.setMaxArea",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.setMaxArea",
      upstreamId: "features2d.mser.set-max-area",
      wasmExport: "setMaxArea",
    },
    {
      implementationOrigin: "original",
      method: "MSER.setMinArea",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.setMinArea",
      upstreamId: "features2d.mser.set-min-area",
      wasmExport: "setMinArea",
    },
    {
      implementationOrigin: "original",
      method: "MSER.setPass2Only",
      module: "features2d",
      notes: "Exact pinned-browser truthiness, undefined return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.MSER.setPass2Only",
      upstreamId: "features2d.mser.set-pass2-only",
      wasmExport: "setPass2Only",
    },
    {
      implementationOrigin: "original",
      method: "createORB",
      module: "features2d",
      notes:
        "Creates a Rust-owned ORB configuration handle with pinned defaults; the official 4.13.0 artifact omits the config-listed static ORB.create binding, and detection and descriptors remain unimplemented.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.ORB.create",
      upstreamId: "features2d.orb.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "ORB.getDefaultName",
      module: "features2d",
      notes: "Exact pinned-browser name, arity, argument errors, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.getDefaultName",
      upstreamId: "features2d.orb.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "ORB.getFastThreshold",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.getFastThreshold",
      upstreamId: "features2d.orb.get-fast-threshold",
      wasmExport: "getFastThreshold",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setEdgeThreshold",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setEdgeThreshold",
      upstreamId: "features2d.orb.set-edge-threshold",
      wasmExport: "setEdgeThreshold",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setFastThreshold",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setFastThreshold",
      upstreamId: "features2d.orb.set-fast-threshold",
      wasmExport: "setFastThreshold",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setFirstLevel",
      module: "features2d",
      notes:
        "Exact pinned-browser signed i32 coercion and non-negative validation with atomic errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setFirstLevel",
      upstreamId: "features2d.orb.set-first-level",
      wasmExport: "setFirstLevel",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setMaxFeatures",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setMaxFeatures",
      upstreamId: "features2d.orb.set-max-features",
      wasmExport: "setMaxFeatures",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setNLevels",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setNLevels",
      upstreamId: "features2d.orb.set-nlevels",
      wasmExport: "setNLevels",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setPatchSize",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setPatchSize",
      upstreamId: "features2d.orb.set-patch-size",
      wasmExport: "setPatchSize",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setScaleFactor",
      module: "features2d",
      notes:
        "Exact pinned-browser F64 input conversion with stored F32 state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setScaleFactor",
      upstreamId: "features2d.orb.set-scale-factor",
      wasmExport: "setScaleFactor",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setScoreType",
      module: "features2d",
      notes:
        "Exact pinned-browser structural enum conversion, raw wire state, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setScoreType",
      upstreamId: "features2d.orb.set-score-type",
      wasmExport: "setScoreType",
    },
    {
      implementationOrigin: "original",
      method: "ORB.setWTA_K",
      module: "features2d",
      notes: "Exact pinned-browser signed i32 coercion, return, arity, and lifecycle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.ORB.setWTA_K",
      upstreamId: "features2d.orb.set-wta-k",
      wasmExport: "setWTA_K",
    },
    {
      implementationOrigin: "original",
      method: "createAgastFeatureDetector",
      module: "features2d",
      notes:
        "Creates a Rust-owned AGAST configuration handle with threshold 10, non-maximum suppression enabled, and OAST 9-16 by default; the official 4.13.0 artifact omits the config-listed static create binding, and keypoint detection remains.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.AgastFeatureDetector.create",
      upstreamId: "features2d.agast-feature-detector.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.getDefaultName",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, return value, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.getDefaultName",
      upstreamId: "features2d.agast-feature-detector.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.getNonmaxSuppression",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, boolean state, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.getNonmaxSuppression",
      upstreamId: "features2d.agast-feature-detector.get-nonmax-suppression",
      wasmExport: "getNonmaxSuppression",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.getThreshold",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, signed i32 state, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.getThreshold",
      upstreamId: "features2d.agast-feature-detector.get-threshold",
      wasmExport: "getThreshold",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.getType",
      module: "features2d",
      notes:
        "Returns the canonical pinned-browser AGAST type enum singleton with exact identity, arity, argument errors, unknown-wire behavior, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.getType",
      upstreamId: "features2d.agast-feature-detector.get-type",
      wasmExport: "getType",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.setNonmaxSuppression",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, undefined return, boolean coercion, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.setNonmaxSuppression",
      upstreamId: "features2d.agast-feature-detector.set-nonmax-suppression",
      wasmExport: "setNonmaxSuppression",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.setThreshold",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, undefined return, signed i32 coercion, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.setThreshold",
      upstreamId: "features2d.agast-feature-detector.set-threshold",
      wasmExport: "setThreshold",
    },
    {
      implementationOrigin: "original",
      method: "AgastFeatureDetector.setType",
      module: "features2d",
      notes:
        "Stores the structural AGAST enum object's signed i32 wire value with exact coercion, undefined return, argument errors, unknown values, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.AgastFeatureDetector.setType",
      upstreamId: "features2d.agast-feature-detector.set-type",
      wasmExport: "setType",
    },
    {
      implementationOrigin: "original",
      method: "createFastFeatureDetector",
      module: "features2d",
      notes:
        "Creates a Rust-owned FAST configuration handle with threshold 10, non-maximum suppression enabled, and type 9-16 by default; the official 4.13.0 artifact omits the config-listed static create binding, and keypoint detection remains.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.FastFeatureDetector.create",
      upstreamId: "features2d.fast-feature-detector.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.getDefaultName",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, return value, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.getDefaultName",
      upstreamId: "features2d.fast-feature-detector.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.getNonmaxSuppression",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, boolean state, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.getNonmaxSuppression",
      upstreamId: "features2d.fast-feature-detector.get-nonmax-suppression",
      wasmExport: "getNonmaxSuppression",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.getThreshold",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, signed i32 state, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.getThreshold",
      upstreamId: "features2d.fast-feature-detector.get-threshold",
      wasmExport: "getThreshold",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.getType",
      module: "features2d",
      notes:
        "Returns the canonical pinned-browser FAST type enum singleton with exact identity, arity, argument errors, unknown-wire behavior, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.getType",
      upstreamId: "features2d.fast-feature-detector.get-type",
      wasmExport: "getType",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.setNonmaxSuppression",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, undefined return, boolean coercion, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.setNonmaxSuppression",
      upstreamId: "features2d.fast-feature-detector.set-nonmax-suppression",
      wasmExport: "setNonmaxSuppression",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.setThreshold",
      module: "features2d",
      notes:
        "Matches the pinned browser binding for exact arity, undefined return, signed i32 coercion, BindingError argument checks, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.setThreshold",
      upstreamId: "features2d.fast-feature-detector.set-threshold",
      wasmExport: "setThreshold",
    },
    {
      implementationOrigin: "original",
      method: "FastFeatureDetector.setType",
      module: "features2d",
      notes:
        "Stores the structural FAST enum object's signed i32 wire value with exact coercion, undefined return, argument errors, unknown values, and deleted-handle behavior.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.FastFeatureDetector.setType",
      upstreamId: "features2d.fast-feature-detector.set-type",
      wasmExport: "setType",
    },
    {
      implementationOrigin: "original",
      method: "createGFTTDetector",
      module: "features2d",
      notes:
        "Creates a Rust-owned GFTT configuration handle with the exact OpenCV 4.13 defaults through one selected six-argument shape; the gradientSize overload remains, the official artifact omits the config-listed static create binding, and feature detection remains.",
      sources: [FEATURES2D_SOURCE],
      status: "partial",
      upstream: "cv.GFTTDetector.create",
      upstreamId: "features2d.gfttdetector.create",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getBlockSize",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, signed 32-bit state, return value, and deleted-handle errors. The browser matrix covers the default, integer-coerced mutations, extra arguments, and lifecycle failures.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getBlockSize",
      upstreamId: "features2d.gfttdetector.get-block-size",
      wasmExport: "getBlockSize",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getDefaultName",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 zero-argument getter, exact Feature2D.GFTTDetector return value, extra-argument rejection, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getDefaultName",
      upstreamId: "features2d.gfttdetector.get-default-name",
      wasmExport: "getDefaultName",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getHarrisDetector",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, boolean state, return value, extra-argument rejection, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getHarrisDetector",
      upstreamId: "features2d.gfttdetector.get-harris-detector",
      wasmExport: "getHarrisDetector",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getK",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, F64 state, return value, extra-argument rejection, and deleted-handle errors, including NaN and infinities.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getK",
      upstreamId: "features2d.gfttdetector.get-k",
      wasmExport: "getK",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getMaxFeatures",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, signed 32-bit state, return value, extra-argument rejection, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getMaxFeatures",
      upstreamId: "features2d.gfttdetector.get-max-features",
      wasmExport: "getMaxFeatures",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getMinDistance",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, F64 state, return value, extra-argument rejection, and deleted-handle errors, including NaN and infinities.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getMinDistance",
      upstreamId: "features2d.gfttdetector.get-min-distance",
      wasmExport: "getMinDistance",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.getQualityLevel",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 getter for zero-argument arity, F64 state, return value, extra-argument rejection, and deleted-handle errors, including NaN and infinities.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.getQualityLevel",
      upstreamId: "features2d.gfttdetector.get-quality-level",
      wasmExport: "getQualityLevel",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setBlockSize",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript-to-i32 coercion, missing and extra argument errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setBlockSize",
      upstreamId: "features2d.gfttdetector.set-block-size",
      wasmExport: "setBlockSize",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setHarrisDetector",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript boolean coercion, missing and extra argument errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setHarrisDetector",
      upstreamId: "features2d.gfttdetector.set-harris-detector",
      wasmExport: "setHarrisDetector",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setK",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript number coercion, NaN and infinity preservation, argument-count errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setK",
      upstreamId: "features2d.gfttdetector.set-k",
      wasmExport: "setK",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setMaxFeatures",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript-to-i32 coercion, missing and extra argument errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setMaxFeatures",
      upstreamId: "features2d.gfttdetector.set-max-features",
      wasmExport: "setMaxFeatures",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setMinDistance",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript number coercion, NaN and infinity preservation, argument-count errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setMinDistance",
      upstreamId: "features2d.gfttdetector.set-min-distance",
      wasmExport: "setMinDistance",
    },
    {
      implementationOrigin: "original",
      method: "GFTTDetector.setQualityLevel",
      module: "features2d",
      notes:
        "Matches the pinned OpenCV.js 4.13.0 one-argument setter, undefined return, JavaScript number coercion, NaN and infinity preservation, argument-count errors, and deleted-handle errors.",
      sources: [FEATURES2D_SOURCE],
      status: "implemented",
      upstream: "cv.GFTTDetector.setQualityLevel",
      upstreamId: "features2d.gfttdetector.set-quality-level",
      wasmExport: "setQualityLevel",
    },
    {
      implementationOrigin: "original",
      method: "getLogLevel",
      module: "core",
      notes:
        "Package-owned WebAssembly-instance log state with levels 0 through 6; the official OpenCV.js 4.13.0 docs artifact does not expose this config-listed binding, so runtime differential verification remains unavailable.",
      sources: [CORE_SOURCE],
      status: "partial",
      upstream: "cv.getLogLevel",
      upstreamId: "core.function.get-log-level",
      wasmExport: "getLogLevel",
    },
    {
      implementationOrigin: "original",
      method: "setLogLevel",
      module: "core",
      notes:
        "Accepts levels 0 through 6, updates package-owned WebAssembly-instance state, and returns the previous level; the official OpenCV.js 4.13.0 docs artifact does not expose this config-listed binding, so runtime differential verification remains unavailable.",
      sources: [CORE_SOURCE],
      status: "partial",
      upstream: "cv.setLogLevel",
      upstreamId: "core.function.set-log-level",
      wasmExport: "setLogLevel",
    },
    {
      implementationOrigin: "original",
      method: "getOptimalDFTSize",
      module: "core",
      notes:
        "Matches the pinned browser's exact one-argument contract, Embind signed i32 coercion and errors, minimal 2-, 3-, and 5-smooth results, negative and zero behavior, and exclusive 2,125,764,000 upper sentinel.",
      sources: [CORE_SOURCE],
      status: "implemented",
      upstream: "cv.getOptimalDFTSize",
      upstreamId: "core.function.get-optimal-dftsize",
      wasmExport: "getOptimalDFTSize",
    },
    {
      implementationOrigin: "original",
      method: "setIdentity",
      module: "core",
      notes:
        "Matches exact overload dispatch, Mat-before-Scalar conversion, array-like Scalar coercion, all shipped depths, one through four channels, typed empties, integer sentinels, signed floating zero, and strided in-place output.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.setIdentity",
      upstreamId: "core.function.set-identity",
      wasmExport: "matSetIdentity",
    },
    {
      implementationOrigin: "original",
      method: "randu",
      module: "core",
      notes:
        "All scalar depths, strided regions, one through four channel-specific half-open ranges, and deterministic in-place fills; the package RNG sequence differs from OpenCV and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.randu",
      upstreamId: "core.function.randu",
      wasmExport: "matRandu",
    },
    {
      implementationOrigin: "original",
      method: "randn",
      module: "core",
      notes:
        "All scalar depths, strided regions, one through four channel-specific means and standard deviations, and deterministic in-place fills; covariance matrices, OpenCV RNG sequences, and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.randn",
      upstreamId: "core.function.randn",
      wasmExport: "matRandn",
    },
    {
      implementationOrigin: "original",
      method: "setRNGSeed",
      module: "core",
      notes:
        "Signed 32-bit seeds replay the package-owned SplitMix64 stream; OpenCV RNG sequences and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.setRNGSeed",
      upstreamId: "core.function.set-rngseed",
      wasmExport: "setRNGSeed",
    },
    {
      implementationOrigin: "original",
      method: "transform",
      module: "core",
      notes:
        "All scalar source depths, one through four input channels, F32/F64 linear or affine coefficients, strided regions, allocation, and mutable destinations; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.transform",
      upstreamId: "core.function.transform",
      wasmExport: "matTransform",
    },
    {
      implementationOrigin: "original",
      method: "perspectiveTransform",
      module: "core",
      notes:
        "F32/F64 two- and three-component vectors, F32/F64 square coefficients, strided regions, allocation, and mutable destinations; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.perspectiveTransform",
      upstreamId: "core.function.perspective-transform",
      wasmExport: "matPerspectiveTransform",
    },
    {
      implementationOrigin: "original",
      method: "determinant",
      module: "core",
      notes:
        "Matches the exact one-argument Mat binding for nonempty square single-channel F32/F64 sources, including compact and strided input preservation, direct 1x1 through 3x3 signed-zero and non-finite results, depth-specific elimination and pivot cutoffs for larger matrices, and invalid, empty, or deleted input errors.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.determinant",
      upstreamId: "core.function.determinant",
      wasmExport: "matDeterminant",
    },
    {
      implementationOrigin: "original",
      method: "invert",
      module: "core",
      notes:
        "Square single-channel inputs at every scalar depth, F32/F64 mutable destinations, and LU, Cholesky, or QR methods; pseudo-inverse methods, non-square inputs, and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.invert",
      upstreamId: "core.function.invert",
      wasmExport: "matInvertInto",
    },
    {
      implementationOrigin: "original",
      method: "solve",
      module: "core",
      notes:
        "Single-channel systems at every input depth, F32/F64 mutable destinations, multiple right-hand sides, and LU, Cholesky, or QR methods; SVD, eigen, normal-equation flags, underdetermined systems, and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.solve",
      upstreamId: "core.function.solve",
      wasmExport: "matSolveInto",
    },
    {
      implementationOrigin: "original",
      method: "meanStdDev",
      module: "core",
      notes:
        "All source depths, per-channel F64 outputs, optional U8 masks, strided regions, and mutable outputs; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.meanStdDev",
      upstreamId: "core.function.mean-std-dev",
      wasmExport: "matMeanStdDevInto",
    },
    {
      implementationOrigin: "original",
      method: "reduce",
      module: "core",
      notes:
        "Both axes, SUM/AVG/MAX/MIN, all source and destination depths, strided regions, and mutable outputs; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.reduce",
      upstreamId: "core.function.reduce",
      wasmExport: "matReduceInto",
    },
    {
      implementationOrigin: "original",
      method: "norm",
      module: "core",
      notes:
        "Single/difference, masked, relative, numeric, Hamming, and Hamming2 forms across all depths; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.norm",
      upstreamId: "core.function.norm",
      wasmExport: "matNorm",
    },
    {
      implementationOrigin: "original",
      method: "normalize",
      module: "core",
      notes:
        "INF/L1/L2/MINMAX modes, masks, every source/destination depth, strided regions, and mutable destinations; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.normalize",
      upstreamId: "core.function.normalize",
      wasmExport: "matNormalizeInto",
    },
    {
      implementationOrigin: "original",
      method: "lut",
      module: "core",
      notes:
        "U8/I8 sources, one or matching table channels, every output depth, strided regions, and mutable destinations; differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.LUT",
      upstreamId: "core.function.lut",
      wasmExport: "matLut",
    },
    {
      implementationOrigin: "original",
      method: "copyMakeBorder",
      module: "core",
      notes:
        "All depths, constant/replicate/reflect/wrap/reflect101 modes, isolated bit, and scalar constants; public destination form remains.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.copyMakeBorder",
      upstreamId: "core.function.copy-make-border",
      wasmExport: "matCopyMakeBorder",
    },
    {
      implementationOrigin: "original",
      method: "addWeighted",
      module: "core",
      notes:
        "Exact six/seven-argument mutable output contract, all scalar depths, mixed-depth dtype conversion, destination replacement, live aliases, typed empties, and CV_32S overflow.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.addWeighted",
      upstreamId: "core.function.add-weighted",
      wasmExport: "matAddWeighted",
    },
    {
      implementationOrigin: "original",
      method: "convertScaleAbs",
      module: "core",
      notes:
        "Exact two/three/four-argument mutable output contract, all scalar input depths, U8 saturation, destination replacement, live aliases, and typed empties.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.convertScaleAbs",
      upstreamId: "core.function.convert-scale-abs",
      wasmExport: "matConvertScaleAbs",
    },
    {
      implementationOrigin: "original",
      method: "divide",
      module: "core",
      notes:
        "Exact three/four/five-argument matrix contract exposed by the pinned artifact, all scalar depths, mixed-depth dtype conversion, destination replacement, live aliases, typed empties, and CV_32S overflow.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.divide",
      upstreamId: "core.function.divide",
      wasmExport: "matDivide",
    },
    {
      implementationOrigin: "original",
      method: "multiply",
      module: "core",
      notes:
        "Exact three/four/five-argument mutable output contract, all scalar depths, mixed-depth dtype conversion, destination replacement, live aliases, typed empties, and CV_32S wrapping.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.multiply",
      upstreamId: "core.function.multiply",
      wasmExport: "matMultiply",
    },
    {
      implementationOrigin: "original",
      method: "hconcat",
      module: "core",
      notes: "Two through four all-depth inputs; MatVector and mutable destination forms remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.hconcat",
      upstreamId: "core.function.hconcat",
      wasmExport: "matHconcat2",
    },
    {
      implementationOrigin: "original",
      method: "vconcat",
      module: "core",
      notes: "Two through four all-depth inputs; MatVector and mutable destination forms remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.vconcat",
      upstreamId: "core.function.vconcat",
      wasmExport: "matVconcat2",
    },
    {
      implementationOrigin: "original",
      method: "cartToPolar",
      module: "core",
      notes:
        "Exact four- or five-argument F32/F64 browser contract with JavaScript boolean coercion, paired destination replacement, typed empty layouts, live single-output aliases, full-rotation angles, multichannel data, and the pinned F32 computation path for both depths. Shared paired outputs and unsafe native integer or canonical-empty calls are rejected before mutation.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.cartToPolar",
      upstreamId: "core.function.cart-to-polar",
      wasmExport: "matCartToPolar",
    },
    {
      implementationOrigin: "original",
      method: "exp",
      module: "core",
      notes:
        "Exact two-argument F32/F64 browser contract with typed empty matrices, destination replacement, detached or shared regions, live overlapping traversal, deleted handles, and IEEE edge values.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.exp",
      upstreamId: "core.function.exp",
      wasmExport: "matExpInto",
    },
    {
      implementationOrigin: "original",
      method: "log",
      module: "core",
      notes:
        "Exact two-argument F32/F64 browser contract with typed empty matrices, destination replacement, detached or shared regions, live overlapping traversal, deleted handles, and IEEE edge values.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.log",
      upstreamId: "core.function.log",
      wasmExport: "matLogInto",
    },
    {
      implementationOrigin: "original",
      method: "magnitude",
      module: "core",
      notes:
        "Exact three-argument F32/F64 browser contract with matching inputs, destination replacement, exact or overlapping aliases to either input, deleted handles, and direct-square overflow, underflow, NaN, infinity, and signed-zero behavior.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.magnitude",
      upstreamId: "core.function.magnitude",
      wasmExport: "matMagnitudeInto",
    },
    {
      implementationOrigin: "original",
      method: "polarToCart",
      module: "core",
      notes:
        "Exact four- or five-argument F32/F64 browser contract with JavaScript boolean coercion, paired destination replacement, typed empty layouts, live single-output aliases, multichannel data, periodic angles, signed magnitudes, and the pinned F32 computation path for both depths. Shared paired outputs and unsafe native integer or canonical-empty calls are rejected before mutation.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.polarToCart",
      upstreamId: "core.function.polar-to-cart",
      wasmExport: "matPolarToCart",
    },
    {
      implementationOrigin: "original",
      method: "pow",
      module: "core",
      notes:
        "Exact three-argument browser contract with Embind F64 exponent conversion, all seven scalar depths for valid powers, typed empty matrices, destination replacement, live aliases, integer saturation or wrapping, and pinned floating-point edge behavior. Unsafe native integer outputs for fractional and non-finite powers are excluded and rejected safely.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.pow",
      upstreamId: "core.function.pow",
      wasmExport: "matPowInto",
    },
    {
      implementationOrigin: "original",
      method: "sqrt",
      module: "core",
      notes:
        "Exact two-argument F32/F64 browser contract with typed and canonical empty matrices, destination replacement, detached or shared regions, live overlapping traversal, deleted handles, and IEEE edge values. Unsafe native integer output is excluded and rejected safely.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.sqrt",
      upstreamId: "core.function.sqrt",
      wasmExport: "matSqrtInto",
    },
    {
      implementationOrigin: "original",
      method: "absdiff",
      module: "core",
      notes: "U8 matrices with matching dimensions and channels; other depths remain missing.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.absdiff",
      upstreamId: "core.function.absdiff",
      wasmExport: "matAbsdiffU8",
    },
    {
      implementationOrigin: "original",
      method: "add",
      module: "core",
      notes:
        "Saturating U8 matrix-to-matrix addition; scalar, mask, dtype, and output forms remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.add",
      upstreamId: "core.function.add",
      wasmExport: "matAddU8",
    },
    {
      implementationOrigin: "original",
      method: "bitwiseAnd",
      module: "core",
      notes: "U8 matrix-to-matrix AND without masks or scalar operands.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.bitwise_and",
      upstreamId: "core.function.bitwise-and",
      wasmExport: "matBitwiseAndU8",
    },
    {
      implementationOrigin: "original",
      method: "bitwiseNot",
      module: "core",
      notes:
        "Exact two- and three-argument browser contract with caller-owned destinations, optional U8/I8 masks, all scalar depths and channel counts, typed empties, raw floating-point bits, strided matrices, aliases, and live unmasked overlapping regions.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.bitwise_not",
      upstreamId: "core.function.bitwise-not",
      wasmExport: "matBitwiseNotInto",
    },
    {
      implementationOrigin: "original",
      method: "bitwiseOr",
      module: "core",
      notes: "U8 matrix-to-matrix OR without masks or scalar operands.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.bitwise_or",
      upstreamId: "core.function.bitwise-or",
      wasmExport: "matBitwiseOrU8",
    },
    {
      implementationOrigin: "original",
      method: "bitwiseXor",
      module: "core",
      notes: "U8 matrix-to-matrix XOR without masks or scalar operands.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.bitwise_xor",
      upstreamId: "core.function.bitwise-xor",
      wasmExport: "matBitwiseXorU8",
    },
    {
      implementationOrigin: "original",
      method: "compareEqual",
      module: "core",
      notes: "U8 equality comparison; the remaining comparison modes and scalar form are missing.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.compare",
      upstreamId: "core.function.compare",
      wasmExport: "matCompareEqU8",
    },
    {
      implementationOrigin: "original",
      method: "countNonZero",
      module: "core",
      notes:
        "Exact one-argument browser contract across every available scalar depth, signed zero, NaN, infinities, subnormal values, empty and deleted matrices, non-contiguous regions, invalid Mat inputs, and semantic multi-channel rejection.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.countNonZero",
      upstreamId: "core.function.count-non-zero",
      wasmExport: "matCountNonZero",
    },
    {
      implementationOrigin: "original",
      method: "flip",
      module: "core",
      notes:
        "Exact three-argument browser contract across all scalar depths, signed flip codes, empty and deleted matrices, destination reallocation, in-place operation, and shared or detached regions.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.flip",
      upstreamId: "core.function.flip",
      wasmExport: "matFlip",
    },
    {
      implementationOrigin: "original",
      method: "arcLength",
      module: "imgproc",
      notes:
        "Exact two-argument browser contract for I32 and F32 contours in Nx1C2, 1xNC2, or Nx2C1 layout, including JavaScript truthiness, open and closed perimeter, deleted inputs, invalid depths and shapes, and safe pre-rejection of unsafe typed-empty paths.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.arcLength",
      upstreamId: "imgproc.function.arc-length",
      wasmExport: "matArcLength",
    },
    {
      implementationOrigin: "original",
      method: "contourArea",
      module: "imgproc",
      notes:
        "Exact one- or two-argument browser contract with runtime length zero for I32 and F32 contours in Nx1C2, 1xNC2, or Nx2C1 layout, including JavaScript truthiness, deleted inputs, invalid depths and shapes, and safe pre-rejection of unsafe typed-empty paths.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.contourArea",
      upstreamId: "imgproc.function.contour-area",
      wasmExport: "matContourArea",
    },
    {
      implementationOrigin: "original",
      method: "boundingRect",
      module: "imgproc",
      notes:
        "Exact one-argument browser contract for I32 and F32 contours in Nx1C2, 1xNC2, or Nx2C1 layout, including floored fractional coordinates, inclusive integer bounds, deleted inputs, invalid depths and shapes, canonical empty bounds, and safe pre-rejection of unsafe typed-empty paths.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.boundingRect",
      upstreamId: "imgproc.function.bounding-rect",
      wasmExport: "matBoundingRect",
    },
    {
      implementationOrigin: "original",
      method: "isContourConvex",
      module: "imgproc",
      notes:
        "Exact one-argument browser contract for continuous I32 and F32 contours in Nx1C2, 1xNC2, or Nx2C1 layout, including strict clockwise and counter-clockwise convexity, collinear, duplicate, concave, self-crossing, small, empty, deleted, invalid-depth, invalid-shape, and non-contiguous inputs.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.isContourConvex",
      upstreamId: "imgproc.function.is-contour-convex",
      wasmExport: "matIsContourConvex",
    },
    {
      implementationOrigin: "original",
      method: "pointPolygonTest",
      module: "imgproc",
      notes:
        "Exact three-argument browser contract for continuous I32 and F32 contours in Nx1C2, 1xNC2, or Nx2C1 layout, including structural Point2f conversion, float32 narrowing, JavaScript truthiness, one-point and segment contours, classification, distance, traversal-dependent signed zero, non-finite query sentinels, empty, deleted, invalid-depth, invalid-shape, and non-contiguous inputs.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.pointPolygonTest",
      upstreamId: "imgproc.function.point-polygon-test",
      wasmExport: "matPointPolygonTest",
    },
    {
      implementationOrigin: "original",
      method: "getStructuringElement",
      module: "imgproc",
      notes:
        "Matches exact two- and three-argument overloads, Embind integer conversion for structural Size and Point values, default and explicit anchors, rectangle, cross, ellipse, and diamond geometry, invalid inputs, and fresh single-channel U8 results.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.getStructuringElement",
      upstreamId: "imgproc.function.get-structuring-element",
      wasmExport: "getStructuringElement",
    },
    {
      implementationOrigin: "original",
      method: "createHanningWindow",
      module: "imgproc",
      notes:
        "Matches the exact destination-first three-argument binding, structural Size and signed i32 type conversion, F32/F64 destination replacement and compatible ROI writes, invalid-input preservation, and pinned cosine-coefficient square-root arithmetic.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.createHanningWindow",
      upstreamId: "imgproc.function.create-hanning-window",
      wasmExport: "createHanningWindowInto",
    },
    {
      implementationOrigin: "original",
      method: "ellipse2Poly",
      module: "imgproc",
      notes:
        "Non-negative integer axes, ordered arc bounds from 0 through 360 degrees, and angular steps from 1 through 180 return deduplicated integer points; arc normalization, swapped bounds, mutable output, and differential fixtures remain.",
      sources: [IMGPROC_SOURCE],
      status: "partial",
      upstream: "cv.ellipse2Poly",
      upstreamId: "imgproc.function.ellipse2-poly",
      wasmExport: "ellipse2Poly",
    },
    {
      implementationOrigin: "original",
      method: "clipLine",
      module: "imgproc",
      notes:
        "Signed 32-bit integer segments clip against positive-size integer rectangles with inclusive pixel bounds; the package returns points instead of mutating caller-owned point objects, and differential fixtures remain.",
      sources: [IMGPROC_SOURCE],
      status: "partial",
      upstream: "cv.clipLine",
      upstreamId: "imgproc.function.clip-line",
      wasmExport: "clipLine",
    },
    {
      implementationOrigin: "original",
      method: "getRotationMatrix2D",
      module: "imgproc",
      notes:
        "Matches the pinned three-argument browser binding: structural Point2f fields are checked in x/y order and narrowed to F32, angle and scale use strict Embind F64 conversion with booleans, signed zero and non-finite values propagate, and each call allocates an independent 2x3 single-channel F64 matrix with exact coefficients.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.getRotationMatrix2D",
      upstreamId: "imgproc.function.get-rotation-matrix2-d",
      wasmExport: "matGetRotationMatrix2D",
    },
    {
      implementationOrigin: "original",
      method: "getAffineTransform",
      module: "imgproc",
      notes:
        "Matches the exact two-Mat binding, continuous F32 point inputs in 3x2C1, 3x1C2, or 1x3C2 layouts, source preservation, singular zero output, non-finite propagation, exact LU arithmetic, and fresh 2x3 F64 results.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.getAffineTransform",
      upstreamId: "imgproc.function.get-affine-transform",
      wasmExport: "matGetAffineTransform",
    },
    {
      implementationOrigin: "original",
      method: "invertAffineTransform",
      module: "imgproc",
      notes:
        "Matches the exact two-Mat mutable binding for 2x3 single-channel F32/F64 inputs, source-depth arithmetic and output, destination replacement, compatible ROI writes, exact aliasing, singular signed zeros, non-finite propagation, and invalid-input behavior.",
      sources: [IMGPROC_SOURCE],
      status: "implemented",
      upstream: "cv.invertAffineTransform",
      upstreamId: "imgproc.function.invert-affine-transform",
      wasmExport: "matInvertAffineTransformInto",
    },
    {
      implementationOrigin: "original",
      method: "getPerspectiveTransform",
      module: "imgproc",
      notes:
        "Four F32 or F64 point pairs in 4x2C1, 4x1C2, or 1x4C2 matrices, including strided regions, allocate a normalized 3x3 F64 map; only one scaled partial-pivoting solve method is present, and differential fixtures remain.",
      sources: [IMGPROC_SOURCE],
      status: "partial",
      upstream: "cv.getPerspectiveTransform",
      upstreamId: "imgproc.function.get-perspective-transform",
      wasmExport: "matGetPerspectiveTransform",
    },
    {
      implementationOrigin: "original",
      method: "cvtColor",
      module: "imgproc",
      notes:
        "U8 mutable Mat conversion for pinned codes 0 through 11, covering RGB/BGR/RGBA/BGRA channel order, alpha insertion or removal, grayscale conversion, dstCn 3/4 selection, compact and strided sources, destination replacement, and exact in-place use; U16, F32, HSV/HLS, YUV, packed, Bayer, and other codes remain.",
      sources: [IMGPROC_COLOR_SOURCE],
      status: "partial",
      upstream: "cv.cvtColor",
      upstreamId: "imgproc.function.cvt-color",
      wasmExport: "matCvtColorInto",
    },
    {
      implementationOrigin: "original",
      method: "inRange",
      module: "core",
      notes: "Inclusive U8 matrix bounds; scalar bounds and other depths remain missing.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.inRange",
      upstreamId: "core.function.in-range",
      wasmExport: "matInRangeU8",
    },
    {
      implementationOrigin: "original",
      method: "max",
      module: "core",
      notes: "U8 matrix-to-matrix maximum; scalar operands and other depths remain missing.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.max",
      upstreamId: "core.function.max",
      wasmExport: "matMaxU8",
    },
    {
      implementationOrigin: "original",
      method: "mean",
      module: "core",
      notes:
        "Exact one- or two-argument browser contract across all scalar depths, one through four channels, optional U8 masks, compact and strided matrices, typed empties, and floating-point edge values.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.mean",
      upstreamId: "core.function.mean",
      wasmExport: "matMean",
    },
    {
      implementationOrigin: "original",
      method: "min",
      module: "core",
      notes: "U8 matrix-to-matrix minimum; scalar operands and other depths remain missing.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.min",
      upstreamId: "core.function.min",
      wasmExport: "matMinU8",
    },
    {
      implementationOrigin: "original",
      method: "minMaxLoc",
      module: "core",
      notes:
        "Exact one- or two-argument browser contract across every scalar depth for single-channel matrices, optional U8 masks, compact and strided matrices, ties, NaN, and canonical or typed empty headers.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.minMaxLoc",
      upstreamId: "core.function.min-max-loc",
      wasmExport: "matMinMaxLoc",
    },
    {
      implementationOrigin: "original",
      method: "resize",
      module: "imgproc",
      notes:
        "Mutable Mat resizing with all-depth nearest-neighbor sampling, half-pixel U8 linear interpolation, U8 area shrinking, explicit dimensions or scale-derived dimensions, compact strided sources, destination replacement, and pinned-browser fixtures; all-depth linear/area plus cubic, Lanczos, and exact modes remain.",
      sources: [IMGPROC_TRANSFORM_SOURCE],
      status: "partial",
      upstream: "cv.resize",
      upstreamId: "imgproc.function.resize",
      wasmExport: "matResizeInto",
    },
    {
      implementationOrigin: "original",
      method: "repeat",
      module: "core",
      notes:
        "Exact four-argument browser contract across all scalar depths, Embind signed repeat-count conversion, empty and deleted matrices, destination replacement, detached incompatible regions, exact in-place rejection, and live overlapping shared regions.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.repeat",
      upstreamId: "core.function.repeat",
      wasmExport: "matRepeat",
    },
    {
      implementationOrigin: "original",
      method: "rotate",
      module: "core",
      notes:
        "Exact three-argument browser contract and constants across all scalar depths, Embind signed code conversion, empty and deleted matrices, destination replacement, in-place operation, detached incompatible regions, and live overlapping shared regions.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.rotate",
      upstreamId: "core.function.rotate",
      wasmExport: "matRotate",
    },
    {
      implementationOrigin: "original",
      method: "subtract",
      module: "core",
      notes: "Saturating U8 matrix subtraction; scalar, mask, dtype, and output forms remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.subtract",
      upstreamId: "core.function.subtract",
      wasmExport: "matSubtractU8",
    },
    {
      implementationOrigin: "original",
      method: "threshold",
      module: "imgproc",
      notes:
        "Mutable U8 Mat destinations for all five fixed threshold modes and single-channel Otsu selection, with returned threshold values and pinned-browser output fixtures; Triangle selection and wider documented depths remain.",
      sources: [IMGPROC_MISC_SOURCE],
      status: "partial",
      upstream: "cv.threshold",
      upstreamId: "imgproc.function.threshold",
      wasmExport: "matThresholdInto",
    },
    {
      implementationOrigin: "original",
      method: "transpose",
      module: "core",
      notes:
        "Exact two-argument browser contract across all scalar depths, empty and deleted matrices, destination reallocation, in-place operation, and shared or detached regions.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.transpose",
      upstreamId: "core.function.transpose",
      wasmExport: "matTranspose",
    },
    {
      implementationOrigin: "original",
      method: "merge",
      module: "core",
      notes:
        "Two through four all-depth Mat inputs are supported; MatVector and caller-provided destination forms remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.merge",
      upstreamId: "core.function.merge",
      wasmExport: "matMerge",
    },
    {
      implementationOrigin: "original",
      method: "mixChannels",
      module: "core",
      notes:
        "All scalar depths, strided regions, alias-safe mutable output, and arbitrary channel pairs for one source and one destination; MatVector input/output forms and differential fixtures remain.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.mixChannels",
      upstreamId: "core.function.mix-channels",
      wasmExport: "matMixChannels",
    },
    {
      implementationOrigin: "original",
      method: "split",
      module: "core",
      notes:
        "All scalar depths, channels, and strided regions are supported; the MatVector destination form remains.",
      sources: [CORE_ARRAY_SOURCE],
      status: "partial",
      upstream: "cv.split",
      upstreamId: "core.function.split",
      wasmExport: "matSplit",
    },
    {
      implementationOrigin: "original",
      method: "trace",
      module: "core",
      notes:
        "Exact one-argument browser contract across all scalar depths, one through four channels, rectangular and strided matrices, typed empties, and floating-point accumulation edge values.",
      sources: [CORE_ARRAY_SOURCE],
      status: "implemented",
      upstream: "cv.trace",
      upstreamId: "core.function.trace",
      wasmExport: "matTrace",
    },
    {
      implementationOrigin: "original",
      method: "createTonemapDrago",
      module: "photo",
      notes:
        "Creates a Rust-owned Drago tone-mapping configuration; the pinned artifact omits the global factory and pixel processing remains unimplemented.",
      sources: [PHOTO_SOURCE],
      status: "partial",
      upstream: "cv.createTonemapDrago",
      upstreamId: "photo.function.create-tonemap-drago",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "createTonemapMantiuk",
      module: "photo",
      notes:
        "Creates a Rust-owned Mantiuk tone-mapping configuration; the pinned artifact omits the global factory and pixel processing remains unimplemented.",
      sources: [PHOTO_SOURCE],
      status: "partial",
      upstream: "cv.createTonemapMantiuk",
      upstreamId: "photo.function.create-tonemap-mantiuk",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "createTonemapReinhard",
      module: "photo",
      notes:
        "Creates a Rust-owned Reinhard tone-mapping configuration; the pinned artifact omits the global factory and pixel processing remains unimplemented.",
      sources: [PHOTO_SOURCE],
      status: "partial",
      upstream: "cv.createTonemapReinhard",
      upstreamId: "photo.function.create-tonemap-reinhard",
      wasmExport: "create",
    },
    {
      implementationOrigin: "original",
      method: "Tonemap.getGamma",
      module: "photo",
      notes: "Exact inherited float32 gamma state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.Tonemap.getGamma",
      upstreamId: "photo.tonemap.get-gamma",
      wasmExport: "getGamma",
    },
    {
      implementationOrigin: "original",
      method: "Tonemap.setGamma",
      module: "photo",
      notes:
        "Exact inherited float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.Tonemap.setGamma",
      upstreamId: "photo.tonemap.set-gamma",
      wasmExport: "setGamma",
    },
    {
      implementationOrigin: "original",
      method: "TonemapDrago.getBias",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapDrago.getBias",
      upstreamId: "photo.tonemap-drago.get-bias",
      wasmExport: "getBias",
    },
    {
      implementationOrigin: "original",
      method: "TonemapDrago.getSaturation",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapDrago.getSaturation",
      upstreamId: "photo.tonemap-drago.get-saturation",
      wasmExport: "getSaturation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapDrago.setBias",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapDrago.setBias",
      upstreamId: "photo.tonemap-drago.set-bias",
      wasmExport: "setBias",
    },
    {
      implementationOrigin: "original",
      method: "TonemapDrago.setSaturation",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapDrago.setSaturation",
      upstreamId: "photo.tonemap-drago.set-saturation",
      wasmExport: "setSaturation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapMantiuk.getSaturation",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapMantiuk.getSaturation",
      upstreamId: "photo.tonemap-mantiuk.get-saturation",
      wasmExport: "getSaturation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapMantiuk.getScale",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapMantiuk.getScale",
      upstreamId: "photo.tonemap-mantiuk.get-scale",
      wasmExport: "getScale",
    },
    {
      implementationOrigin: "original",
      method: "TonemapMantiuk.setSaturation",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapMantiuk.setSaturation",
      upstreamId: "photo.tonemap-mantiuk.set-saturation",
      wasmExport: "setSaturation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapMantiuk.setScale",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapMantiuk.setScale",
      upstreamId: "photo.tonemap-mantiuk.set-scale",
      wasmExport: "setScale",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.getColorAdaptation",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.getColorAdaptation",
      upstreamId: "photo.tonemap-reinhard.get-color-adaptation",
      wasmExport: "getColorAdaptation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.getIntensity",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.getIntensity",
      upstreamId: "photo.tonemap-reinhard.get-intensity",
      wasmExport: "getIntensity",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.getLightAdaptation",
      module: "photo",
      notes: "Exact float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.getLightAdaptation",
      upstreamId: "photo.tonemap-reinhard.get-light-adaptation",
      wasmExport: "getLightAdaptation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.setColorAdaptation",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.setColorAdaptation",
      upstreamId: "photo.tonemap-reinhard.set-color-adaptation",
      wasmExport: "setColorAdaptation",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.setIntensity",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.setIntensity",
      upstreamId: "photo.tonemap-reinhard.set-intensity",
      wasmExport: "setIntensity",
    },
    {
      implementationOrigin: "original",
      method: "TonemapReinhard.setLightAdaptation",
      module: "photo",
      notes: "Exact float conversion, float32 state, arity, return, and lifetime behavior.",
      sources: [PHOTO_SOURCE],
      status: "implemented",
      upstream: "cv.TonemapReinhard.setLightAdaptation",
      upstreamId: "photo.tonemap-reinhard.set-light-adaptation",
      wasmExport: "setLightAdaptation",
    },
    {
      implementationOrigin: "original",
      method: "GaussianBlur",
      module: "imgproc",
      notes:
        "Mutable U8 destinations with odd separable kernels, derived or explicit sigmas, interleaved channels, and supported border modes; wider depths and exact small-kernel coverage remain.",
      sources: ["https://docs.opencv.org/4.13.0/d4/d86/group__imgproc__filter.html"],
      status: "partial",
      upstream: "cv.GaussianBlur",
      upstreamId: "imgproc.function.gaussian-blur",
      wasmExport: "matGaussianBlurInto",
    },
    {
      implementationOrigin: "original",
      method: "morphologyEx",
      module: "imgproc",
      notes:
        "U8 erosion, dilation, opening, closing, gradient, top-hat, and black-hat over explicit kernels, anchors, iterations, border modes, and mutable destinations; HITMISS and wider depths remain.",
      sources: ["https://docs.opencv.org/4.13.0/d4/d86/group__imgproc__filter.html"],
      status: "partial",
      upstream: "cv.morphologyEx",
      upstreamId: "imgproc.function.morphology-ex",
      wasmExport: "matMorphologyExInto",
    },
    {
      implementationOrigin: "original",
      method: "Sobel",
      module: "imgproc",
      notes:
        "U8 sources with first and second 3x3 derivatives, scaling, delta, supported border modes, and U8/I16/F32/F64 destinations; other source depths and kernel sizes remain.",
      sources: ["https://docs.opencv.org/4.13.0/d4/d86/group__imgproc__filter.html"],
      status: "partial",
      upstream: "cv.Sobel",
      upstreamId: "imgproc.function.sobel",
      wasmExport: "matSobelInto",
    },
    {
      implementationOrigin: "original",
      method: "Canny",
      module: "imgproc",
      notes:
        "Single-channel U8 images with 3x3 Sobel gradients, L1 or L2 magnitude, directional non-maximum suppression, double thresholds, eight-neighbor hysteresis, and mutable U8 edge destinations; other apertures and derivative-input overloads remain.",
      sources: ["https://docs.opencv.org/4.13.0/dd/d1a/group__imgproc__feature.html"],
      status: "partial",
      upstream: "cv.Canny",
      upstreamId: "imgproc.function.canny",
      wasmExport: "matCannyInto",
    },
    {
      implementationOrigin: "original",
      method: "approxPolyDP",
      module: "imgproc",
      notes:
        "Iterative Ramer–Douglas–Peucker simplification of finite I32/F32 open or closed curves in Nx1C2, 1xNC2 and Nx2C1 continuous matrices; mutable destinations, ROI output and aliases. Closed-curve start/retained vertex choices and non-finite input behavior differ from the pinned browser; wider numerical and error contracts remain unverified.",
      sources: [
        "https://docs.opencv.org/4.13.0/d3/dc0/group__imgproc__shape.html",
        "https://doi.org/10.3138/FM57-6770-U75U-7727",
      ],
      status: "partial",
      upstream: "cv.approxPolyDP",
      upstreamId: "imgproc.function.approx-poly-dp",
      wasmExport: "matApproxPolyDPInto",
    },
    {
      implementationOrigin: "original",
      method: "findContours",
      module: "imgproc",
      notes:
        "Single-channel U8 masks, holes and nested islands, RETR_EXTERNAL/LIST/CCOMP/TREE, CHAIN_APPROX_NONE/SIMPLE, exact sibling/point order, offsets, strided sources and empty-output clearing. Source/hierarchy aliasing uses a snapshot and differs from the pinned browser; I32 label input, FLOODFILL and Teh-Chin approximation remain.",
      sources: ["https://docs.opencv.org/4.13.0/d3/dc0/group__imgproc__shape.html"],
      status: "partial",
      upstream: "cv.findContours",
      upstreamId: "imgproc.function.find-contours",
      wasmExport: "matFindContoursInto",
    },
    {
      implementationOrigin: "original",
      method: "warpAffine",
      module: "imgproc",
      notes:
        "U8 sources with F32 or F64 2x3 transforms, mutable destinations, nearest or linear sampling, constant or replicate borders, scalar border values, and forward or inverse-map flags; wider source depths, additional borders, and bit-exact interpolation modes remain.",
      sources: [IMGPROC_TRANSFORM_SOURCE],
      status: "partial",
      upstream: "cv.warpAffine",
      upstreamId: "imgproc.function.warp-affine",
      wasmExport: "matWarpAffineInto",
    },
    {
      implementationOrigin: "original",
      method: "equalizeHist",
      module: "imgproc",
      notes:
        "Single-channel U8 histogram equalization with a Rust-owned cumulative histogram and lookup table, mutable destinations, constant-image preservation, and pinned-browser differential evidence; CLAHE is a separate unimplemented family.",
      sources: [IMGPROC_HISTOGRAM_SOURCE],
      status: "partial",
      upstream: "cv.equalizeHist",
      upstreamId: "imgproc.function.equalize-hist",
      wasmExport: "matEqualizeHistInto",
    },
    {
      implementationOrigin: "not-started",
      method: "warpPerspective",
      module: "imgproc",
      notes: "Perspective transforms are not implemented.",
      sources: [IMGPROC_TRANSFORM_SOURCE],
      status: "planned",
      upstream: "cv.warpPerspective",
      upstreamId: "imgproc.function.warp-perspective",
    },
    {
      implementationOrigin: "original",
      method: "matchTemplate",
      module: "imgproc",
      notes:
        "All six methods for finite U8/F32 images with one through four channels, optional binary U8 or weighted F32 masks, per-channel means, F32 destinations, and strided inputs/outputs. Browser fixtures cover zero norms and location recovery. Destination aliases snapshot inputs and differ from the pinned template/result-overlap behavior; exhaustive floating-point and error contracts remain.",
      sources: ["https://docs.opencv.org/4.13.0/df/dfb/group__imgproc__object.html"],
      status: "partial",
      upstream: "cv.matchTemplate",
      upstreamId: "imgproc.function.match-template",
      wasmExport: "matMatchTemplateInto",
    },
  ],
  inventoryPolicy: "Independently authored from public documentation and runtime behavior",
  packageVersion: "0.2.0",
  schemaVersion: 2,
} as const satisfies ParityManifest;
